// File generated by hand from the Firebase console config files
// (android/app/google-services.json, ios/Runner/GoogleService-Info.plist) —
// normally produced by running `flutterfire configure`, which needs an
// interactive Firebase CLI login this environment doesn't have. Only
// Android and iOS are configured (no Firebase app was registered for web/
// Windows/macOS/Linux), matching what push notifications are actually
// needed for in this app.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'no Firebase web app was registered for this project.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcAzDAceEqyMuSlrPc06GPo_o6sTKLrHE',
    appId: '1:223780920045:android:680ee054f4286806f20ae4',
    messagingSenderId: '223780920045',
    projectId: 'freshmandi-b584e',
    storageBucket: 'freshmandi-b584e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtOiQ3Dy2qhYWJyb_6Lq75CktT6gvTF5g',
    appId: '1:223780920045:ios:86cc5031d09bc445f20ae4',
    messagingSenderId: '223780920045',
    projectId: 'freshmandi-b584e',
    storageBucket: 'freshmandi-b584e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
